version: '3.8'

services:
  node-app:
    build:
      context: .
    volumes:
      # Mount the local app directory to the /code/app directory in the container    
      - .:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - MODE
